// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEhSSW5qRnQxaGRWeDVEWXYvTUxoU3BQakxnVms2N2VCNStLbjNiQmtIMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiODBWYW5FT1JXSG1oRGhISVVyQzJlQW05MFJKWWZyV2JjajZNanZWRVJBdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXQU9MSlVxTzI3ZmJnSy9zN3IyWjZWOFo3WjZPZVZGSWY2QnYveEFKbDNnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJYVnBQWkpTVWl5UXl3YzNmcmhBUi9scU9mS0htQ1lUSzdDeW1QRnM3REJzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitKb004M1hPL2NTSjBMNVpJdnZPbEFpUzNMRHFCV2VxQ3hjYVFrTi9jbTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldUWi95cEEwc3d3NkhaTkNSVzNpUUIyMWk5Y1ljMkNvT21tVjh5N252SGM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkNRdTZpM3dGSHJtUUJJYmd1d3JWaVVGNTFwQSt6cnFSQkZUWnIyaWlIND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZzBoQWdsZlQ1Rldma04zNUh3dGJINmxFY2VMTXZIdlZpZHJhT2NqM1ZXTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImUrc2VXbTFmcm1WREJ5SE5zcnd5cjZzQ1ludmVmZE1jalVqaVdROEZYc2lVMThnMEJrczFMVU9GN09ncTJTKytpUmEva01OdllrNmpSNEZvQXJoSmdBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTksImFkdlNlY3JldEtleSI6Ik1wRXo3OUdMZDFUbjBrcVRGZjEyZE1EemlLcE9vUGc3cUF4RU5YQzREUkE9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0NzA0NTY4MTU0M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5NjI5M0FENThFMDAxREFGRTU3NENEODQ5NEFCNzVFQyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMzNjE5MDAyfV0sIm5leHRQcmVLZXlJZCI6NjEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo2MSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJPWDZZbElScVJsR3U0Z2NXRGhUaU5RIiwicGhvbmVJZCI6ImE5YjRlYzRhLTNkNGEtNDhjNS05NmFlLWZiOGM4NjlkNGE4ZSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIvYkdjbXB6QmFsNUlCNXpQUGQyRlhFMmNsSm89In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSGlNbUZLMUJEZTZNNyt0WXR1NGc3czZza044PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjhKV1pNVFhHIiwibWUiOnsiaWQiOiIyMzQ3MDQ1NjgxNTQzOjRAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi4pig77iP4Ly68J2UmPCdlKvwnZSH8J2UovCdlJ7wnZSH8J+SgPCdlI7wnZSm8J2Uq/CdlIrgvLvimKDvuI8ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ01yY202c0VFS3JhMDdvR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ik5xbHpHZzIvRVh3NERzTFQ3YjdUbXRxTll5M1pUOEZMaVZqMGNIZFB5WGs9IiwiYWNjb3VudFNpZ25hdHVyZSI6IllBN2RtNElObkNqQW1ybjQ3aTYvc2tTVzIwQXJxalNibk50YzVHTmFqeFVTa29VM00yQjYzbHVPYjRIalE1VE9ZeDZUUlZZSXk1K2IrZ3lyUXhpK0JRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJpMERTQ0V5T2VKbnZjOVlEeGFDS25FYnRTQmp3WCtaQnN1SUlGMWZXRzdmZStidys4TjhoQUcvVnMycjBod3oybDJXYXVaQVFTUGg1WEdiYlcrSm5qZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDcwNDU2ODE1NDM6NEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJUYXBjeG9OdnhGOE9BN0MwKzIrMDVyYWpXTXQyVS9CUzRsWTlIQjNUOGw1In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMzNjE4OTk5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQVBYaSJ9",
  PREFIX: process.env.PREFIX || '',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "self",
  OWNER_NAME: process.env.OWNER_NAME || "Hitmanlogs",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "2347045681543",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
